/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ExceptionModels.AddressEmpty;
import ExceptionModels.DateOfBirthEmpty;
import ExceptionModels.DistrictEmpty;
import ExceptionModels.FirstNameEmpty;
import ExceptionModels.GenderEmpty;
import ExceptionModels.LastNameEmpty;
import ExceptionModels.NICNumberEmpty;
import ExceptionModels.StudentIDEmpty;
import Models.CertificateStudent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Tharnickanth
 */
public class EntrollCertificateStudentUI extends javax.swing.JFrame {

    String Gender, Program, Program1;
    public EntrollCertificateStudentUI() {
        initComponents();
        ShowCertificateStudent();
        
        Toolkit toolkit = getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }
    public ArrayList<CertificateStudent> StudentList() {

        ArrayList<CertificateStudent> certificateStudentList = new ArrayList();

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query1 = "Select * from CertificateStudentInformatation";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            CertificateStudent certificateStudent;
            while (rs.next()) {

                certificateStudent = new CertificateStudent(rs.getString("FirstName"), rs.getString("LastName"), rs.getString("Address"), rs.getString("District"), rs.getString("DOB"), rs.getString("NIC"), rs.getString("Gender"), rs.getString("Email"), rs.getString("Telephone"), rs.getString("SID"), rs.getString("Program"));
                certificateStudentList.add(certificateStudent);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return certificateStudentList;
    }
    public void ShowCertificateStudent() {
        ArrayList<CertificateStudent> StudentList1 = StudentList();
        DefaultTableModel model = (DefaultTableModel) CertificateStudenttable.getModel();
        Object[] Column = new Object[11];

        for (int x = 0; x < StudentList1.size(); x++) {
            Column[0] = StudentList1.get(x).StudentID;
            Column[1] = StudentList1.get(x).FirstName;
            Column[2] = StudentList1.get(x).LastName;
            Column[3] = StudentList1.get(x).Address;
            Column[4] = StudentList1.get(x).District;
            Column[5] = StudentList1.get(x).DOB;
            Column[6] = StudentList1.get(x).NIC;
            Column[7] = StudentList1.get(x).Gender;
            Column[8] = StudentList1.get(x).Email;
            Column[9] = StudentList1.get(x).TelephoneNo;
            Column[10] = StudentList1.get(x).Program;
            model.addRow(Column);

        }
    }
    
    public void clearData()
    {
        txtFirstName2.setText("");
        txtLastName2.setText("");
        txtAddress2.setText("");
        txtDistrict2.setText("");
        txtNIC2.setText("");
        txtSID2.setText("");
        txtEmail2.setText("");
        txtTelephone2.setText("");
        buttonGroup1.clearSelection();
        comProgram2.setSelectedIndex(0);
        DateDOB2.setCalendar(null);
        txtSearch2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastName2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDistrict2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DateDOB2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtNIC2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Female2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelephone2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSID2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comProgram2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtSearch2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CertificateStudenttable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        Male2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(48, 167, 232));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log off");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Personal Informatation");

        jLabel2.setText("First Name :");

        jLabel3.setText("Last Name :");

        jLabel4.setText("Address :");

        txtAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress2ActionPerformed(evt);
            }
        });

        jLabel5.setText("District :");

        jLabel6.setText("Date of Birth :");

        jLabel7.setText("NIC Number :");

        jLabel8.setText("Gender :");

        buttonGroup1.add(Female2);
        Female2.setText("Female");

        jLabel9.setText("E-mail :");

        jLabel10.setText("Telephone :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Course Informatation");

        jLabel12.setText("Student ID :");

        jLabel13.setText("Program :");

        comProgram2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Certificate in Computer Network and security", "Certificate in Professional Computer Applications", "Certificate Android Application Development", "Certificate in  Graphic Designing", "Certificate in Computer Hardware Technician", "Certificate in Social Sciences", "Advanced Certificate in Science", "Certificate in English for Business", "Certificate in AutoCAD", "Certificate Programme in laboratory Technology" }));

        jLabel14.setText("Event ID :");

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        CertificateStudenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "First Name", "Last Name", "Address", "District", "Date of Birth", "NIC", "Gender", "E-mail", "Telephone", "Program"
            }
        ));
        CertificateStudenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CertificateStudenttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CertificateStudenttable);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Certificate Student Information");

        buttonGroup1.add(Male2);
        Male2.setText("Male");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFirstName2)
                                            .addComponent(txtLastName2)
                                            .addComponent(txtAddress2)
                                            .addComponent(txtDistrict2)
                                            .addComponent(DateDOB2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                            .addComponent(txtNIC2)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Male2)
                                                .addGap(18, 18, 18)
                                                .addComponent(Female2))
                                            .addComponent(txtEmail2)
                                            .addComponent(txtTelephone2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(jButton3))
                                            .addComponent(txtSID2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comProgram2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton7)))))
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(403, 403, 403)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDistrict2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(DateDOB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNIC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Female2)
                                .addComponent(Male2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTelephone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(comProgram2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel14)
                    .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into CertificateStudentInformatation(SID,FirstName,LastName,Address,District,DOB,NIC,Gender,Email,Program,Telephone) values(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtSID2.getText());
            pst.setString(2, txtFirstName2.getText());
            pst.setString(3, txtLastName2.getText());
            pst.setString(4, txtAddress2.getText());
            pst.setString(5, txtDistrict2.getText());
            if (txtFirstName2.getText().equals("")) {
                throw new FirstNameEmpty();
            } else if (txtLastName2.getText().equals("")) {
                throw new LastNameEmpty();
            } else if (txtAddress2.getText().equals("")) {
                throw new AddressEmpty();
            } else if (txtDistrict2.getText().equals("")) {
                throw new DistrictEmpty();
            }
            
            if (DateDOB2.getDate() == null) {
                throw new DateOfBirthEmpty();
            } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(DateDOB2.getDate());
            pst.setString(6,date);
            }
            
            pst.setString(7, txtNIC2.getText());
            if (txtNIC2.getText().equals("")) {
                throw new NICNumberEmpty();
            }
            if (buttonGroup1.getSelection() == null) {
                throw new GenderEmpty();
            } else {
            if (Male2.isSelected()) {
                Gender = "Male";
            }
            if (Female2.isSelected()) {
                Gender = "Female";
            }
            }
            pst.setString(8, Gender);
            pst.setString(9, txtEmail2.getText());
            Program = comProgram2.getSelectedItem().toString();
            pst.setString(10, Program);
            pst.setString(11, txtTelephone2.getText());
            if (txtSID2.getText().equals("")) {
                throw new StudentIDEmpty();
            }
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) CertificateStudenttable.getModel();
            model.setRowCount(0);
            ShowCertificateStudent();
            clearData();
            JOptionPane.showMessageDialog(rootPane, "Inserted Sucessfully!!!", "Message", 1);
     
        }catch (ClassNotFoundException e1) {
            JOptionPane.showMessageDialog(null, e1);
        } catch (SQLException e2) {
            JOptionPane.showMessageDialog(null, e2);
        } catch (FirstNameEmpty e3) {
            JOptionPane.showMessageDialog(rootPane, e3.getMessage(), "Message", 2);
        } catch (LastNameEmpty e4) {
            JOptionPane.showMessageDialog(rootPane, e4.getMessage(), "Message", 2);
        } catch (AddressEmpty e5) {
            JOptionPane.showMessageDialog(rootPane, e5.getMessage(), "Message", 2);
        } catch (DistrictEmpty e6) {
            JOptionPane.showMessageDialog(rootPane, e6.getMessage(), "Message", 2);
        } catch (DateOfBirthEmpty e7) {
            JOptionPane.showMessageDialog(rootPane, e7.getMessage(), "Message", 2);
        } catch (NICNumberEmpty e8) {
            JOptionPane.showMessageDialog(rootPane, e8.getMessage(), "Message", 2);
        } catch (GenderEmpty e9) {
            JOptionPane.showMessageDialog(rootPane, e9.getMessage(), "Message", 2);
        } catch (StudentIDEmpty e10) {
            JOptionPane.showMessageDialog(rootPane, e10.getMessage(), "Message", 2);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        clearData();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "update CertificateStudentInformatation set FirstName=?,LastName=?,Address=?,District=?,DOB=?,NIC=?,Gender=?,Email=?,Program=?,Telephone=? where SID=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(11, txtSID2.getText());
            pst.setString(1, txtFirstName2.getText());
            pst.setString(2, txtLastName2.getText());
            pst.setString(3, txtAddress2.getText());
            pst.setString(4, txtDistrict2.getText());
            if (txtFirstName2.getText().equals("")) {
                throw new FirstNameEmpty();
            } else if (txtLastName2.getText().equals("")) {
                throw new LastNameEmpty();
            } else if (txtAddress2.getText().equals("")) {
                throw new AddressEmpty();
            } else if (txtDistrict2.getText().equals("")) {
                throw new DistrictEmpty();
            }
            if (DateDOB2.getDate() == null) {
                throw new DateOfBirthEmpty();
            } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(DateDOB2.getDate());
            pst.setString(5, date);
            }
            pst.setString(6, txtNIC2.getText());
            if (txtNIC2.getText().equals("")) {
                throw new NICNumberEmpty();
            } 
            
            if (buttonGroup1.getSelection() == null) {
                throw new GenderEmpty();
            } else {
            if (Male2.isSelected()) {
                Gender = "Male";
            }
            if (Female2.isSelected()) {
                Gender = "Female";
            }
            }
            pst.setString(7, Gender);
            pst.setString(8, txtEmail2.getText());
            Program = comProgram2.getSelectedItem().toString();
            pst.setString(9, Program);
            pst.setString(10, txtTelephone2.getText());
            if (txtSID2.getText().equals("")) {
                throw new StudentIDEmpty();
            }
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) CertificateStudenttable.getModel();
            model.setRowCount(0);
            ShowCertificateStudent();
            clearData();
            JOptionPane.showMessageDialog(rootPane, "Update Sucessfully!!!", "Message", 1);

        } catch (ClassNotFoundException e1) {
            JOptionPane.showMessageDialog(null, e1);
        } catch (SQLException e2) {
            JOptionPane.showMessageDialog(null, e2);
        } catch (FirstNameEmpty e3) {
            JOptionPane.showMessageDialog(rootPane, e3.getMessage(), "Message", 2);
        } catch (LastNameEmpty e4) {
            JOptionPane.showMessageDialog(rootPane, e4.getMessage(), "Message", 2);
        } catch (AddressEmpty e5) {
            JOptionPane.showMessageDialog(rootPane, e5.getMessage(), "Message", 2);
        } catch (DistrictEmpty e6) {
            JOptionPane.showMessageDialog(rootPane, e6.getMessage(), "Message", 2);
        } catch (DateOfBirthEmpty e7) {
            JOptionPane.showMessageDialog(rootPane, e7.getMessage(), "Message", 2);
        } catch (NICNumberEmpty e8) {
            JOptionPane.showMessageDialog(rootPane, e8.getMessage(), "Message", 2);
        } catch (GenderEmpty e9) {
            JOptionPane.showMessageDialog(rootPane, e9.getMessage(), "Message", 2);
        } catch (StudentIDEmpty e10) {
            JOptionPane.showMessageDialog(rootPane, e10.getMessage(), "Message", 2);
        
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "Select * from CertificateStudentInformatation where SID=? or NIC=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtSearch2.getText());
            pst.setString(2, txtSearch2.getText());
            ResultSet rs = pst.executeQuery();
            CertificateStudent cs;
            while (rs.next()) {
                cs = new CertificateStudent(rs.getString("FirstName"), rs.getString("LastName"), rs.getString("Address"), rs.getString("District"), rs.getString("DOB"), rs.getString("NIC"), rs.getString("Gender"), rs.getString("Email"), rs.getString("Telephone"), rs.getString("SID"), rs.getString("Program"));
                txtFirstName2.setText(cs.FirstName);
                txtLastName2.setText(cs.LastName);
                txtAddress2.setText(cs.Address);
                txtDistrict2.setText(cs.District);
                txtEmail2.setText(cs.Email);
                txtNIC2.setText(cs.NIC);
                txtSID2.setText(cs.StudentID);
                txtTelephone2.setText(cs.TelephoneNo);

                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(cs.DOB);
                DateDOB2.setDate(date);

          
                if (cs.Gender.equals("Male")) {
                    Male2.setSelected(true);
                }
                if (cs.Gender.equals("Female")) {
                    Female2.setSelected(true);
                }
                String Prg = cs.Program;
                switch (Prg)
                {
                    case "Certificate in Computer Network and security":comProgram2.setSelectedIndex(0);break;
                    case "Certificate in Professional Computer Applications":comProgram2.setSelectedIndex(1);break;
                    case "Certificate Android Application Development":comProgram2.setSelectedIndex(2);break;
                    case "Certificate in  Graphic Designing":comProgram2.setSelectedIndex(3);break;
                    case "Certificate in Computer Hardware Technician":comProgram2.setSelectedIndex(4);break;
                    case "Certificate in Social Sciences":comProgram2.setSelectedIndex(5);break;
                    case "Advanced Certificate in Science":comProgram2.setSelectedIndex(6);break;
                    case "Certificate in English for Business":comProgram2.setSelectedIndex(7);break;
                    case "Certificate in AutoCAD":comProgram2.setSelectedIndex(8);break;
                    case "Certificate Programme in laboratory Technology":comProgram2.setSelectedIndex(8);break;
                }
            }
        

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "delete CertificateStudentInformatation where SID=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtSID2.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) CertificateStudenttable.getModel();
            model.setRowCount(0);
            ShowCertificateStudent();
            clearData();
            JOptionPane.showMessageDialog(rootPane, "Delete Sucessfully!!!", "Message", 1);
        }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EntrollStudentHomeUI esh = new EntrollStudentHomeUI();
        esh.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginUI login = new LoginUI();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CertificateStudenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CertificateStudenttableMouseClicked
        int i = CertificateStudenttable.getSelectedRow();
        TableModel modle = CertificateStudenttable.getModel();
        txtSID2.setText(modle.getValueAt(i, 0).toString());
        txtFirstName2.setText(modle.getValueAt(i, 1).toString());
        txtLastName2.setText(modle.getValueAt(i, 2).toString());
        txtAddress2.setText(modle.getValueAt(i, 3).toString());
        txtDistrict2.setText(modle.getValueAt(i, 4).toString());
        try {     
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) modle.getValueAt(i, 5));
            DateDOB2.setDate(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        txtNIC2.setText(modle.getValueAt(i, 6).toString());
        String sex = modle.getValueAt(i, 7).toString();
        if (sex.equals("Male")) {
            Male2.setSelected(true);
        }
        if (sex.equals("Female")) {
            Female2.setSelected(true);
        }
        txtEmail2.setText(modle.getValueAt(i, 8).toString());
        txtTelephone2.setText(modle.getValueAt(i, 9).toString());
        String Prg = modle.getValueAt(i, 10).toString();
        switch (Prg) {
            case "Certificate in Computer Network and security":
                comProgram2.setSelectedIndex(0);
                break;
            case "Certificate in Professional Computer Applications":
                comProgram2.setSelectedIndex(1);
                break;
            case "Certificate Android Application Development":
                comProgram2.setSelectedIndex(2);
                break;
            case "Certificate in  Graphic Designing":
                comProgram2.setSelectedIndex(3);
                break;
            case "Certificate in Computer Hardware Technician":
                comProgram2.setSelectedIndex(4);
                break;
             case "Certificate in Social Sciences":
                comProgram2.setSelectedIndex(5);
                break;
            case "Advanced Certificate in Science":
                comProgram2.setSelectedIndex(6);
                break;
            case "Certificate in English for Business":
                comProgram2.setSelectedIndex(7);
                break;
            case "Certificate in AutoCAD":
                comProgram2.setSelectedIndex(8);
                break;
            case "Certificate Programme in laboratory Technology":
                comProgram2.setSelectedIndex(9);
                break;
        }
        
    }//GEN-LAST:event_CertificateStudenttableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntrollCertificateStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntrollCertificateStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntrollCertificateStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntrollCertificateStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntrollCertificateStudentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CertificateStudenttable;
    private com.toedter.calendar.JDateChooser DateDOB2;
    private javax.swing.JRadioButton Female2;
    private javax.swing.JRadioButton Male2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comProgram2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtDistrict2;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtFirstName2;
    private javax.swing.JTextField txtLastName2;
    private javax.swing.JTextField txtNIC2;
    private javax.swing.JTextField txtSID2;
    private javax.swing.JTextField txtSearch2;
    private javax.swing.JTextField txtTelephone2;
    // End of variables declaration//GEN-END:variables
}
