/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ExceptionModels.AddressEmpty;
import ExceptionModels.DateOfBirthEmpty;
import ExceptionModels.DistrictEmpty;
import ExceptionModels.FirstNameEmpty;
import ExceptionModels.GenderEmpty;
import ExceptionModels.LastNameEmpty;
import ExceptionModels.NICNumberEmpty;
import ExceptionModels.StudentIDEmpty;
import Models.PostgraduateStudent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Tharnickanth
 */
public class EntrollPostgraduateStudentUI extends javax.swing.JFrame {

    String Gender, Program, Program1;
    public EntrollPostgraduateStudentUI() {
        initComponents();
        ShowPostgraduateStudent();
        
        Toolkit toolkit = getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }
    public ArrayList<PostgraduateStudent> StudentList() {

        ArrayList<PostgraduateStudent> postgraduateStudentList = new ArrayList();

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query1 = "Select * from PostGraduateStudentInformatation";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            PostgraduateStudent postgraduateStudent;
            while (rs.next()) {

                postgraduateStudent = new PostgraduateStudent(rs.getString("FirstName"), rs.getString("LastName"), rs.getString("Address"), rs.getString("District"), rs.getString("DOB"), rs.getString("NIC"), rs.getString("Gender"), rs.getString("Email"), rs.getString("Telephone"), rs.getString("SID"), rs.getString("Program"));
                postgraduateStudentList.add(postgraduateStudent);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return postgraduateStudentList;
    }
    public void ShowPostgraduateStudent() {
        ArrayList<PostgraduateStudent> StudentList1 = StudentList();
        DefaultTableModel model = (DefaultTableModel) PostgraduateStudenttable.getModel();
        Object[] Column = new Object[11];

        for (int x = 0; x < StudentList1.size(); x++) {
            Column[0] = StudentList1.get(x).StudentID;
            Column[1] = StudentList1.get(x).FirstName;
            Column[2] = StudentList1.get(x).LastName;
            Column[3] = StudentList1.get(x).Address;
            Column[4] = StudentList1.get(x).District;
            Column[5] = StudentList1.get(x).DOB;
            Column[6] = StudentList1.get(x).NIC;
            Column[7] = StudentList1.get(x).Gender;
            Column[8] = StudentList1.get(x).Email;
            Column[9] = StudentList1.get(x).TelephoneNo;
            Column[10] = StudentList1.get(x).Program;
            model.addRow(Column);

        }
    }
    
    public void clearData()
    {
         txtFirstName1.setText("");
        txtLastName1.setText("");
        txtAddress1.setText("");
        txtDistrict1.setText("");
        txtNIC1.setText("");
        txtSID1.setText("");
        txtEmail1.setText("");
        txtTelephone1.setText("");
        buttonGroup1.clearSelection();
        comProgram1.setSelectedIndex(0);
        DateDOB1.setCalendar(null);
        txtSearch1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastName1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDistrict1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DateDOB1 = new com.toedter.calendar.JDateChooser();
        txtNIC1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Male1 = new javax.swing.JRadioButton();
        Female1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelephone1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSID1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSearch1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PostgraduateStudenttable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        comProgram1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 169, 234));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log off");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Personal Informatation");

        jLabel2.setText("First Name :");

        jLabel3.setText("Last Name :");

        jLabel4.setText("Address :");

        txtAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress1ActionPerformed(evt);
            }
        });

        jLabel5.setText("District");

        jLabel6.setText("Date of Birth :");

        jLabel7.setText("NIC Number :");

        jLabel8.setText("Gender :");

        buttonGroup1.add(Male1);
        Male1.setText("Male");

        buttonGroup1.add(Female1);
        Female1.setText("Female");

        jLabel9.setText("E-mail :");

        jLabel10.setText("Telephone :");

        txtTelephone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephone1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Course Informatation");

        jLabel12.setText("Student ID :");

        jLabel13.setText("Program :");

        jLabel14.setText("Student ID / NIC :");

        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        PostgraduateStudenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SID", "FirstName", "LastName", "Address", "District", "Date of Birth", "NIC", "Gender", "E-mail", "Telephone ", "Program"
            }
        ));
        PostgraduateStudenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PostgraduateStudenttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PostgraduateStudenttable);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Postgraduate Student Information");

        comProgram1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Msc in Computer Science", "MBA in Human Resource Management", "Master of Energy Management", "Master of Science in Environmental Science", "Master of Science in Structural Engineering" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(404, 404, 404)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(comProgram1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSID1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(87, 87, 87))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jButton4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton7))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton3)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel10))
                                            .addGap(21, 21, 21)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(Male1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Female1))
                                                .addComponent(txtFirstName1)
                                                .addComponent(txtLastName1)
                                                .addComponent(txtAddress1)
                                                .addComponent(txtDistrict1)
                                                .addComponent(DateDOB1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                .addComponent(txtNIC1)
                                                .addComponent(txtEmail1)
                                                .addComponent(txtTelephone1))))
                                    .addGap(56, 56, 56)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDistrict1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(DateDOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Male1)
                            .addComponent(Female1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTelephone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtSID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(comProgram1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress1ActionPerformed

    private void txtTelephone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephone1ActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EntrollStudentHomeUI esh = new EntrollStudentHomeUI();
        esh.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginUI login = new LoginUI();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into PostGraduateStudentInformatation(SID,FirstName,LastName,Address,District,DOB,NIC,Gender,Email,Program,Telephone) values(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtSID1.getText());
            pst.setString(2, txtFirstName1.getText());
            pst.setString(3, txtLastName1.getText());
            pst.setString(4, txtAddress1.getText());
            pst.setString(5, txtDistrict1.getText());
            if (txtFirstName1.getText().equals("")) {
                throw new FirstNameEmpty();
            } else if (txtLastName1.getText().equals("")) {
                throw new LastNameEmpty();
            } else if (txtAddress1.getText().equals("")) {
                throw new AddressEmpty();
            } else if (txtDistrict1.getText().equals("")) {
                throw new DistrictEmpty();
            }
            
            if (DateDOB1.getDate() == null) {
                throw new DateOfBirthEmpty();
            } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(DateDOB1.getDate());
            pst.setString(6, date);
            }
            
            pst.setString(7, txtNIC1.getText());
            if (txtNIC1.getText().equals("")) {
                throw new NICNumberEmpty();
            }
            
            if (buttonGroup1.getSelection() == null) {
                throw new GenderEmpty();
            } else {
            if (Male1.isSelected()) {
                Gender = "Male";
            }
            if (Female1.isSelected()) {
                Gender = "Female";
            }
            }
            
            pst.setString(8, Gender);
            pst.setString(9, txtEmail1.getText());
            Program = comProgram1.getSelectedItem().toString();
            pst.setString(10, Program);
            pst.setString(11, txtTelephone1.getText());
            if (txtSID1.getText().equals("")) {
                throw new StudentIDEmpty();
            }
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) PostgraduateStudenttable.getModel();
            model.setRowCount(0);
            ShowPostgraduateStudent();
            clearData();
            JOptionPane.showMessageDialog(rootPane, "Inserted Sucessfully!!!", "Message", 1);
        
        }catch (ClassNotFoundException e1) {
            JOptionPane.showMessageDialog(null, e1);
        } catch (SQLException e2) {
            JOptionPane.showMessageDialog(null, e2);
        } catch (FirstNameEmpty e3) {
            JOptionPane.showMessageDialog(rootPane, e3.getMessage(), "Message", 2);
        } catch (LastNameEmpty e4) {
            JOptionPane.showMessageDialog(rootPane, e4.getMessage(), "Message", 2);
        } catch (AddressEmpty e5) {
            JOptionPane.showMessageDialog(rootPane, e5.getMessage(), "Message", 2);
        } catch (DistrictEmpty e6) {
            JOptionPane.showMessageDialog(rootPane, e6.getMessage(), "Message", 2);
        } catch (DateOfBirthEmpty e7) {
            JOptionPane.showMessageDialog(rootPane, e7.getMessage(), "Message", 2);
        } catch (NICNumberEmpty e8) {
            JOptionPane.showMessageDialog(rootPane, e8.getMessage(), "Message", 2);
        } catch (GenderEmpty e9) {
            JOptionPane.showMessageDialog(rootPane, e9.getMessage(), "Message", 2);
        } catch (StudentIDEmpty e10) {
            JOptionPane.showMessageDialog(rootPane, e10.getMessage(), "Message", 2);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            clearData();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "update PostGraduateStudentInformatation set FirstName=?,LastName=?,Address=?,District=?,DOB=?,NIC=?,Gender=?,Email=?,Program=?,Telephone=? where SID=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(11, txtSID1.getText());
            pst.setString(1, txtFirstName1.getText());
            pst.setString(2, txtLastName1.getText());
            pst.setString(3, txtAddress1.getText());
            pst.setString(4, txtDistrict1.getText());
            if (txtSID1.getText().equals("")) {
                throw new StudentIDEmpty();
            }else if (txtFirstName1.getText().equals("")) {
                throw new FirstNameEmpty();
            } else if (txtLastName1.getText().equals("")) {
                throw new LastNameEmpty();
            } else if (txtAddress1.getText().equals("")) {
                throw new AddressEmpty();
            } else if (txtDistrict1.getText().equals("")) {
                throw new DistrictEmpty();
            }
             if (DateDOB1.getDate() == null) {
                throw new DateOfBirthEmpty();
            } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(DateDOB1.getDate());
            pst.setString(5, date);
             }
            pst.setString(6, txtNIC1.getText());
            if (txtNIC1.getText().equals("")) {
                throw new NICNumberEmpty();
            } 
            if (buttonGroup1.getSelection() == null) {
                throw new GenderEmpty();
            } else {
            if (Male1.isSelected()) {
                Gender = "Male";
            }
            if (Female1.isSelected()) {
                Gender = "Female";
            }
            }
            pst.setString(7, Gender);
            pst.setString(8, txtEmail1.getText());
            Program = comProgram1.getSelectedItem().toString();
            pst.setString(9, Program);
            pst.setString(10, txtTelephone1.getText());
            
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) PostgraduateStudenttable.getModel();
            model.setRowCount(0);
            ShowPostgraduateStudent();
            clearData();
            JOptionPane.showMessageDialog(rootPane, "Update Sucessfully!!!", "Message", 1);
        
        }catch (ClassNotFoundException e1) {
            JOptionPane.showMessageDialog(null, e1);
        } catch (SQLException e2) {
            JOptionPane.showMessageDialog(null, e2);
        } catch (FirstNameEmpty e3) {
            JOptionPane.showMessageDialog(rootPane, e3.getMessage(), "Message", 2);
        } catch (LastNameEmpty e4) {
            JOptionPane.showMessageDialog(rootPane, e4.getMessage(), "Message", 2);
        } catch (AddressEmpty e5) {
            JOptionPane.showMessageDialog(rootPane, e5.getMessage(), "Message", 2);
        } catch (DistrictEmpty e6) {
            JOptionPane.showMessageDialog(rootPane, e6.getMessage(), "Message", 2);
        } catch (DateOfBirthEmpty e7) {
            JOptionPane.showMessageDialog(rootPane, e7.getMessage(), "Message", 2);
        } catch (NICNumberEmpty e8) {
            JOptionPane.showMessageDialog(rootPane, e8.getMessage(), "Message", 2);
        } catch (GenderEmpty e9) {
            JOptionPane.showMessageDialog(rootPane, e9.getMessage(), "Message", 2);
        } catch (StudentIDEmpty e10) {
            JOptionPane.showMessageDialog(rootPane, e10.getMessage(), "Message", 2);
        
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "Select * from PostGraduateStudentInformatation where SID=? or NIC=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtSearch1.getText());
            pst.setString(2, txtSearch1.getText());
            ResultSet rs = pst.executeQuery();
            PostgraduateStudent pgs;
            while (rs.next()) {
                pgs = new PostgraduateStudent(rs.getString("FirstName"), rs.getString("LastName"), rs.getString("Address"), rs.getString("District"), rs.getString("DOB"), rs.getString("NIC"), rs.getString("Gender"), rs.getString("Email"), rs.getString("Telephone"), rs.getString("SID"), rs.getString("Program"));
                txtFirstName1.setText(pgs.FirstName);
                txtLastName1.setText(pgs.LastName);
                txtAddress1.setText(pgs.Address);
                txtDistrict1.setText(pgs.District);
                txtEmail1.setText(pgs.Email);
                txtNIC1.setText(pgs.NIC);
                txtSID1.setText(pgs.StudentID);
                txtTelephone1.setText(pgs.TelephoneNo);

                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(pgs.DOB);
                DateDOB1.setDate(date);

          
                if (pgs.Gender.equals("Male")) {
                    Male1.setSelected(true);
                }
                if (pgs.Gender.equals("Female")) {
                    Female1.setSelected(true);
                }
                String Prg = pgs.Program;
                switch (Prg)
                {
                    case "Master of Computer Science":comProgram1.setSelectedIndex(0);break;
                    case "MBA in Human Resource Management":comProgram1.setSelectedIndex(1);break;
                    case "Master of Energy Management":comProgram1.setSelectedIndex(2);break;
                    case "Master of Science in Environmental Science":comProgram1.setSelectedIndex(3);break;
                    case "Master of Science in Structural Engineering":comProgram1.setSelectedIndex(4);break;
                }
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "delete PostGraduateStudentInformatation where SID=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtSID1.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) PostgraduateStudenttable.getModel();
            model.setRowCount(0);
            ShowPostgraduateStudent();
            clearData();
            JOptionPane.showMessageDialog(rootPane, "Delete Sucessfully!!!", "Message", 1);
        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void PostgraduateStudenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PostgraduateStudenttableMouseClicked
        int i = PostgraduateStudenttable.getSelectedRow();
        TableModel modle = PostgraduateStudenttable.getModel();
        txtSID1.setText(modle.getValueAt(i, 0).toString());
        txtFirstName1.setText(modle.getValueAt(i, 1).toString());
        txtLastName1.setText(modle.getValueAt(i, 2).toString());
        txtAddress1.setText(modle.getValueAt(i, 3).toString());
        txtDistrict1.setText(modle.getValueAt(i, 4).toString());
        try {
            int srow = PostgraduateStudenttable.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) modle.getValueAt(i, 5));
            DateDOB1.setDate(date);
            txtNIC1.setText(modle.getValueAt(i, 6).toString());
            String sex = modle.getValueAt(i, 7).toString();
        if (sex.equals("Male")) {
            Male1.setSelected(true);
        }
        if (sex.equals("Female")) {
            Female1.setSelected(true);
        }
        txtEmail1.setText(modle.getValueAt(i, 8).toString());
        txtTelephone1.setText(modle.getValueAt(i, 9).toString());
        String Prg = modle.getValueAt(i, 10).toString();
        switch (Prg) {
            case "Master of Computer Science":
                comProgram1.setSelectedIndex(0);
                break;
            case "MBA in Human Resource Management":
                comProgram1.setSelectedIndex(1);
                break;
            case "Master of Energy Management":
                comProgram1.setSelectedIndex(2);
                break;
            case "Master of Science in Environmental Science":
                comProgram1.setSelectedIndex(3);
                break;
            case "Master of Science in Structural Engineering":
                comProgram1.setSelectedIndex(4);
                break;
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PostgraduateStudenttableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntrollPostgraduateStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntrollPostgraduateStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntrollPostgraduateStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntrollPostgraduateStudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntrollPostgraduateStudentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateDOB1;
    private javax.swing.JRadioButton Female1;
    private javax.swing.JRadioButton Male1;
    private javax.swing.JTable PostgraduateStudenttable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comProgram1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtDistrict1;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtFirstName1;
    private javax.swing.JTextField txtLastName1;
    private javax.swing.JTextField txtNIC1;
    private javax.swing.JTextField txtSID1;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtTelephone1;
    // End of variables declaration//GEN-END:variables
}
