/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import ExceptionModels.EventDateEmpty;
import ExceptionModels.EventIDEmpty;
import ExceptionModels.EventMessageEmpty;
import ExceptionModels.EventNameEmpty;
import Models.Event;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Tharnickanth
 */
public class EventListUI extends javax.swing.JFrame {


    public EventListUI() {
        initComponents();
        ShowEvent();
        
        Toolkit toolkit = getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }
    public ArrayList<Event> EventList() {

        ArrayList<Event> eventList = new ArrayList();

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query1 = "Select * from EventInformatation";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            Event event;
            while (rs.next()) {

                event = new Event(rs.getString("ename"),rs.getString("eID"),rs.getString("Description"),rs.getString("Message"),rs.getString("EventDate"),rs.getString("sTime"),rs.getString("eTime"),rs.getString("Venue"));
                eventList.add(event);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return eventList;
    }
    public void ShowEvent() {
        ArrayList<Event> EventList1 = EventList();
        DefaultTableModel model = (DefaultTableModel) EventTable.getModel();
        Object[] Column = new Object[8];

        for (int x = 0; x < EventList1.size(); x++) {
            Column[0] = EventList1.get(x).eID;
            Column[1] = EventList1.get(x).ename;
            Column[2] = EventList1.get(x).Description;
            Column[3] = EventList1.get(x).Message;
            Column[4] = EventList1.get(x).Eventdate;
            Column[5] = EventList1.get(x).StartTime;
            Column[6] = EventList1.get(x).EndTime;
            Column[7] = EventList1.get(x).Venue;
            model.addRow(Column);

        }
    }
    public void cleardata()
    {
        txtEventName.setText("");
        txtEventID.setText("");
        comDesciption.setSelectedIndex(0);
        txtMessage.setText("");
        Date.setCalendar(null);
        txtStartTime.setText("");
        txtEndTime.setText("");
        txtVenue.setText("");
        txtSearch.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEventName = new javax.swing.JTextField();
        comDesciption = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        Date = new com.toedter.calendar.JDateChooser();
        txtStartTime = new javax.swing.JTextField();
        txtEndTime = new javax.swing.JTextField();
        txtVenue = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtEventID = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        EventTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 169, 234));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create / modify  Event List");

        jLabel3.setText("Event Name :");

        jLabel4.setText("Description :");

        jLabel5.setText("Message :");

        jLabel6.setText("Date :");

        jLabel7.setText("StartTime :");

        jLabel8.setText("End Time :");

        jLabel9.setText("Venue :");

        comDesciption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Culture Event", "Organization Event", "Special Event" }));

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Event ID :");

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        EventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EID", "Event Name", "Description", "Message", "Date", "Start Time", "End Time ", "Venue"
            }
        ));
        EventTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(EventTable);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Log off");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel12.setText("Event ID :");

        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(438, 438, 438)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtVenue)
                                .addComponent(txtEndTime)
                                .addComponent(txtStartTime)
                                .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(comDesciption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEventID)
                                .addComponent(txtEventName)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jButton6)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(12, 12, 12)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton5)
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtEventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtEventID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comDesciption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        HomeUI home = new HomeUI();
        home.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        LoginUI login = new LoginUI();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into EventInformatation(eID,eName,Description,Message,EventDate,sTime,eTime,Venue) values(?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            if (txtEventName.getText().equals("")) {
                throw new EventNameEmpty();
            } else if (txtEventID.getText().equals("")) {
                throw new EventIDEmpty();
            } else if (txtMessage.getText().equals("")) {
                throw new EventMessageEmpty();
            } 
            pst.setString(1, txtEventID.getText());  
            pst.setString(2, txtEventName.getText());         
            pst.setString(3, comDesciption.getSelectedItem().toString());
            pst.setString(4, txtMessage.getText());
            if (Date.getDate() == null) {
                throw new EventDateEmpty();
            } else {
            SimpleDateFormat ed = new SimpleDateFormat("yyyy-MM-dd");
            String date = ed.format(Date.getDate());
            pst.setString(5, date);
            }
            pst.setString(6, txtStartTime.getText());
            pst.setString(7, txtEndTime.getText());
            pst.setString(8, txtVenue.getText());
            
            pst.executeUpdate();
            
            DefaultTableModel model = (DefaultTableModel) EventTable.getModel();
            model.setRowCount(0);
            ShowEvent();
            cleardata();
            JOptionPane.showMessageDialog(rootPane, "Event Inserted Sucessfully!!!", "Message", 1);

        } catch (ClassNotFoundException e1) {
            JOptionPane.showMessageDialog(null, e1);
        } catch (SQLException e2) {
            JOptionPane.showMessageDialog(null, e2);
        } catch (EventNameEmpty e3) {
            JOptionPane.showMessageDialog(rootPane, e3.getMessage(), "Message", 2);
        } catch (EventIDEmpty e4) {
            JOptionPane.showMessageDialog(rootPane, e4.getMessage(), "Message", 2);
        } catch (EventMessageEmpty e5) {
            JOptionPane.showMessageDialog(rootPane, e5.getMessage(), "Message", 2);
        } catch (EventDateEmpty e6) {
            JOptionPane.showMessageDialog(rootPane, e6.getMessage(), "Message", 2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "update EventInformatation set eName=?,Description=?,Message=?,EventDate=?,sTime=?,eTime=?,Venue=? where eID=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(8, txtEventID.getText());
            pst.setString(1, txtEventName.getText());            
            pst.setString(2, comDesciption.getSelectedItem().toString());
            pst.setString(3, txtMessage.getText()); 
            SimpleDateFormat ed = new SimpleDateFormat("yyyy-MM-dd");
            String date = ed.format(Date.getDate());
            pst.setString(4, date);      
            pst.setString(5, txtStartTime.getText());
            pst.setString(6, txtEndTime.getText());
            pst.setString(7, txtVenue.getText());
            pst.executeUpdate();
            
            DefaultTableModel model = (DefaultTableModel) EventTable.getModel();
            model.setRowCount(0);
            ShowEvent();
            cleardata();
            JOptionPane.showMessageDialog(rootPane, "Update Sucessfully!!!", "Message", 1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "Select * from EventInformatation where eID=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtSearch.getText());
            ResultSet rs = pst.executeQuery();
            Event e;
            while (rs.next()) {
                e = new Event(rs.getString("ename"),rs.getString("eID"),rs.getString("Description"),rs.getString("Message"),rs.getString("EventDate"),rs.getString("sTime"),rs.getString("eTime"),rs.getString("Venue"));
                txtEventName.setText(e.ename);
                txtEventID.setText(e.eID);
                txtMessage.setText(e.Message);
                
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(e.Eventdate);
                Date.setDate(date);
                txtStartTime.setText(e.StartTime);
                txtEndTime.setText(e.EndTime);
                txtVenue.setText(e.Venue);
                
                String dec =e.Description;
                switch (dec)
                {
                    case "Culture Event":comDesciption.setSelectedIndex(0);break;
                    case "Organization Event":comDesciption.setSelectedIndex(1);break;
                    case "Special Event":comDesciption.setSelectedIndex(2);break;
                }
               
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=master;user=sa;password=tharni12";
            Connection con = DriverManager.getConnection(url);
            String query = "delete EventInformatation where eID=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, txtEventID.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) EventTable.getModel();
            model.setRowCount(0);
            ShowEvent();
            cleardata();
            JOptionPane.showMessageDialog(rootPane, "Delete Sucessfully!!!", "Message", 1);
        }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EventTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventTableMouseClicked
        int i = EventTable.getSelectedRow();
        TableModel modle = EventTable.getModel();
        txtEventID.setText(modle.getValueAt(i, 0).toString());
        txtEventName.setText(modle.getValueAt(i, 1).toString());
        String dec = modle.getValueAt(i, 2).toString();
        switch (dec)
            {
                case "Culture Event":comDesciption.setSelectedIndex(0);break;
                case "Organization Event":comDesciption.setSelectedIndex(1);break;
                case "Special Event":comDesciption.setSelectedIndex(2);break;
            }
        txtMessage.setText(modle.getValueAt(i, 3).toString());
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) modle.getValueAt(i, 4));
            Date.setDate(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
       } 
        txtStartTime.setText(modle.getValueAt(i, 5).toString());
        txtEndTime.setText(modle.getValueAt(i, 6).toString());
        txtVenue.setText(modle.getValueAt(i, 7).toString());
    }//GEN-LAST:event_EventTableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cleardata();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventListUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JTable EventTable;
    private javax.swing.JComboBox<String> comDesciption;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtEndTime;
    private javax.swing.JTextField txtEventID;
    private javax.swing.JTextField txtEventName;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
